version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: nexus-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - nexus-network
    restart: unless-stopped

networks:
  nexus-network:
    driver: bridge

volumes:
  mongodb_data:
